# Dockerfile.dev
FROM bskjon/azuljava:21

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        ca-certificates \
        fuse3 \
        libfuse2 \
        procps \
        jq \
        gnupg && \
    rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://repo.jotta.us/public.gpg | gpg --dearmor -o /usr/share/keyrings/jotta.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/jotta.gpg] https://repo.jotta.us/debian debian main" \
        > /etc/apt/sources.list.d/jotta.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        jotta-cli \
        gocryptfs && \
    rm -rf /var/lib/apt/lists/*


RUN mkdir -p /data /crypt-backend /crypt /config /usr/share/app

VOLUME ["/data", "/crypt-backend", "/config"]

RUN mkdir -p /docker-entrypoint.d

#RUN mkdir -p /docker-entrypoint.d && \
#    printf '%s\n' \
#    '#!/bin/sh' \
#    'echo "[japp] Starter jottad..."' \
#    'jottad &' \
#    'sleep 2' \
#    '' \
#    > /docker-entrypoint.d/10-start-jottad.sh && \
#    chmod +x /docker-entrypoint.d/10-start-jottad.sh


ENV BACKUP_ROOT=/data


EXPOSE 8080

CMD ["java", "-jar", "/usr/share/app/app.jar"]
